mode: predict
debug: False
experiment_name: quick_inference_unirig_skin_unified
resume_from_checkpoint: experiments/skin/articulation-xl/model.ckpt

components:
  data: quick_inference
  transform: inference_skin_transform
  model: unirig_skin
  system: skin
  data_name: predict_skeleton.npz # 固定名: 原流処理互換

writer:
  __target__: skin
  output_dir: results
  add_num: False
  repeat: 1
  save_name: predict
  export_npz: predict_skin # 固定名: スキンウェイトデータ
  export_fbx: result_fbx # 固定名: 原流処理互換

trainer:
  num_nodes: 1
  devices: 1
  precision: bf16-mixed
  accelerator: gpu
  strategy: auto
  inference_mode: True