# UniRig MVP Configuration (Project Restart - Simplified)
# Lessons Learned: Keep configuration minimal, expand only after MVP success

# --- Core Pipeline Settings ---
working_directory_base: "./pipeline_work"

# --- Stage 1: Mesh Extraction (WORKING) ---
mesh_extraction:
  extract_output_subdir: "01_extracted_mesh"
  output_npz_filename: "{model_name}_raw_data.npz"
  num_runs: 1 
  faces_target_count: 1500000

# --- Stage 2: Skeleton Generation (WORKING) ---
skeleton_generation:
  skeleton_output_subdir: "02_skeleton_output"
  task_config_template: "configs/task/quick_inference_skeleton_articulationxl_ar_256.yaml"
  seed: 42
  output_npz_filename: "predict_skeleton.npz"
  output_fbx_filename: "skeleton.fbx"
  output_txt_filename: "skeleton_pred.txt"

# --- Stage 3: Skinning Generation (WORKING) ---
skinning_prediction:
  skin_output_subdir: "03_skinning_output"
  task_config_template: "configs/task/quick_inference_unirig_skin.yaml"
  seed: 42
  output_skinned_fbx_filename: "skinned_model.fbx"
  output_skinning_npz_filename: "predict_skin.npz"

# --- Stage 4: Simple Merging (TO BE IMPLEMENTED) ---
model_merging:
  merge_output_subdir: "04_final_rigged_model"
  output_merged_fbx_filename: "final_rigged_model.fbx"

# --- Web Interface ---
gradio_interface:
  server_name: "0.0.0.0"
  server_port: 7860
  share: false
